### ISSUE TITLE
Anki Tag-Toggler feedback/request

### ISSUE THREAD

**Issue by dedu6ka** [ohspite/anki-tag-toggler#1]
It is my first time here  and i am not a programmer :-(  
This is what I have tried to do in the Original 'Quick_Tagging' addon, but it did not work:

'j': {'tags': '0121_03',  'after': 'suspend'}
'k': {'tags': '0123_05'},  
'l': {'tags': '0125*07'},   it is  date and Interval joined by the asterisk.  It worked.

It worked  in a test without the  (  'after': 'suspend'  ) !  

Would be nice to have 6-7 shortcuts , all with 'Suspend' option.  
Reason:  when Anki Interval is not acceptable, i bypass it with one of my 3 workarounds.  
Your new addon will be the Fastest of 3 - if you can 'fulfill my wish' - even though i am two weeks late  
with my wish -:)  

PS. Of course it would be ideal if an add-on gave me an option to enter an Interval during review !!!  

Thank you.

**Comment by donm** [comment]
Hi @dedu6ka.  

Make sure that you have a comma after every closing brace for the shortcut dicts.  It should look something like this:

```
tag_shortcuts = {
    'H': {'tags': 'hard', 'action': 'toggle'},
    'T': {'tags': 'TODO', 'after': 'bury'},
    'A': {'tags': 'easy', 'after': 'suspend'},
}
```

If that doesn't help, then can you paste the entire definition of `tag_shortcuts` that you're using in your configuration?  When you paste it in, if you put three backticks on the line above and below the code then github will formats it nicely.  

Also, let me know which keyboard shortcuts don't work and what happens when you push them (nothing, an error message, ...).  

Thanks!

**Comment by dedu6ka** [comment]
Thank you, Don, for your reply ! 
I understand why you have not addressed my direct questions :-)

At the end, this is what worked:

tag_shortcuts = {
   'v': {'tags':  '-01-23<see--failed>20_C?', 'after': 'suspend'},
   'n': {'tags':  '-01-25<see--failed>20_C?', 'after': 'suspend'},
   'm': {'tags':' -01-28<see--failed>20_C?', 'after': 'suspend'},
     'j': {'tags': '-01-31<see--failed>20_C?', 'after': 'suspend'},
   'p': {'tags': 'paper-2-4-7-10-20', 'after': 'suspend'},    

The BIG problem though - 
you Suspend the  NOTE rather then  a card. 

The fact that Anki tags ALL cards of a Note  is bad but there is a workaround: 
which is -- keep siblings in separate decks. 

## Thanks again.

On Thu, 1/21/16, Don March notifications@github.com wrote:

 Subject: Re: [anki-tag-toggler] Anki Tag-Toggler feedback/request (#1)
 To: "ohspite/anki-tag-toggler" anki-tag-toggler@noreply.github.com
 Cc: "dedu6ka" vrem2003-temporary@yahoo.com
 Date: Thursday, January 21, 2016, 9:34 PM

 Hi @dedu6ka.  

 Make sure that you have a comma after every closing brace
 for the shortcut dicts.  It should look something like
 this:

 tag_shortcuts = {
     'H': {'tags': 'hard',
 'action': 'toggle'},
     'T': {'tags': 'TODO',
 'after': 'bury'},
     'A': {'tags': 'easy',
 'after': 'suspend'},
 }

 If that doesn't help, then can you paste the entire
 definition of tag_shortcuts that you're
 using in your configuration?  When you paste it in, if you
 put three backticks on the line above and below the code
 then github will formats it nicely.  

 Also, let me know which keyboard shortcuts don't work
 and what happens when you push them (nothing, an error
 message, ...).  

 Thanks!

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by donm** [comment]
Glad you got it working.  Is the only problem now that you'd like to be able to suspend an individual card instead of a note?  If so, I'll add that to my to do list.  It should be pretty easy.

**Comment by dedu6ka** [comment]
>  Is the only problem now that you'd like to be able to suspend an individual card instead of a note?  
> Yes, for now.  
> Thank you, Don

**Comment by donm** [comment]
Check out the new version on Ankiweb, @dedu6ka.  Hopefully it takes care of what you are looking for.

**Comment by dedu6ka** [comment]
Thank you, Don. 
I do not know what to click on on /dedu6ka site :-(  

Are you replying to my Anki Forum "Error message" ?  
If yes, can you tell me how to modify my 'h' shortcut and why id did not work ? 

## Thanks.

On Mon, 1/25/16, Don March notifications@github.com wrote:

 Subject: Re: [anki-tag-toggler] Anki Tag-Toggler feedback/request (#1)
 To: "ohspite/anki-tag-toggler" anki-tag-toggler@noreply.github.com
 Cc: "dedu6ka" vrem2003-temporary@yahoo.com
 Date: Monday, January 25, 2016, 3:31 PM

 Check out the new version on
 Ankiweb, @dedu6ka.  Hopefully
 it takes care of what you are looking for.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by donm** [comment]
I meant that the feature you requested is now uploaded to the add-on page on Ankiweb: https://ankiweb.net/shared/info/874498171

To upgrade, I think you have to delete the current add-on from Anki, and then re-install.  You will lose your configuration in the process, so be sure copy the keybindings you added and paste them into the configuration section of the new version.  I'll work on making that easier in the future.

When someone puts an `@` in front of your username, like `@dedu6ka`, it's just a way of officially referring to you in a conversation.  When it happens the system might automatically notify you that someone mentioned you in a comment.  

I responded to your other questions on the Anki forums.
